WIP: rocksdb
lbryio/herald.go pull request #29
Opened 2021-12-07 03:31 UTC by jeffreypicard

2022-01-17 14:39 UTC, lyoshenka requested changes
i skimmed and it looks fine to me. anything in particular that you wanted me to focus on?

one nit: plz make it clear that the stuff in `resources` dir is actually for testing. maybe call it `testdata` instead?

2022-01-17 14:39 UTC, lyoshenka commented on .gitattributes
> +resources/ filter=lfs diff=lfs merge=lfs -text
what are you using git-lfs for?

2022-01-17 14:39 UTC, lyoshenka commented on go.mod
> +	github.com/lbryio/lbry.go v1.1.2
if you're using lbry.go, please use the v3 branch and update your code accordingly. its the one that's most up to date and depends on the latest lbcd

2022-01-17 14:39 UTC, lyoshenka commented on go.mod
> +	github.com/lbryio/lbry.go v1.1.2
https://github.com/lbryio/lbry.go/tree/v3

2022-01-17 15:18 UTC, jeffreypicard commented on .gitattributes
> +resources/ filter=lfs diff=lfs merge=lfs -text
Oops, I need to remove this. Originally I was planning on use git-lfs when I was going to put binary files in there for testing. After switching to human readable csvs we don't need it.

2022-01-17 15:21 UTC, jeffreypicard commented
> i skimmed and it looks fine to me. anything in particular that you wanted me to focus on?
> 
> one nit: plz make it clear that the stuff in `resources` dir is actually for testing. maybe call it `testdata` instead?

I'll switch it to testdata. `resources` is a leftover habit from when I was writing a lot of enterprise Java/Scala, JVM language repos seem to generally put non source code test data in a directory called `resources`

2022-01-17 15:23 UTC, jeffreypicard commented
> > i skimmed and it looks fine to me. anything in particular that you wanted me to focus on?
> > one nit: plz make it clear that the stuff in `resources` dir is actually for testing. maybe call it `testdata` instead?
> 
> I'll switch it to testdata. `resources` is a leftover habit from when I was writing a lot of enterprise Java/Scala, JVM language repos seem to generally put non source code test data in a directory called `resources`



> i skimmed and it looks fine to me. anything in particular that you wanted me to focus on?

I guess mostly the stuff around trying to make generic functions for the Key,Value pairs based on the type constants. I tried to remove as much duplicated code as I could, but wanted to make sure I was doing that in an efficient / idiomatic way.

2022-02-26 16:53 UTC, steverusso commented
Fwiw, the [zero value](https://go.dev/ref/spec#The_zero_value) for `int` is `0` and for pointers and slices is `nil`. Therefore:
* the ` = nil` is unnecessary in places such as [here](https://github.com/lbryio/hub/pull/29/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R124) and [here](https://github.com/lbryio/hub/pull/29/files#diff-30c25f2a7d8ae335d2aada4b0a6013ad9d159595bb6a2a14b1d0022451b6753fR1100-R1101).
* ints could be initialized more concisely in places such as [here](https://github.com/lbryio/hub/pull/29/files#diff-a3f4b6041601807543c4326d820592ebb0d88692a4c0f3d98d70dd3600018db8R75) and [here](https://github.com/lbryio/hub/pull/29/files#diff-30c25f2a7d8ae335d2aada4b0a6013ad9d159595bb6a2a14b1d0022451b6753fR380) with `var i int` or `i := 0`.

2022-03-24 21:55 UTC, lyoshenka reviewed
there's no need to prefix numerical variables with `n`. in `func(nFields int)`, it should just be `fields int`. its clear that that's a number.

please add godoc comments. you don't have to comment every single function, but most types and most functions over 10 lines should have them. at the very very least, a paragraph at the top of each package describing that package

lots of TODO and FIXME comments still there, plus chunks of commented-out code. please clean them up

2022-03-24 21:55 UTC, lyoshenka commented on db/prefixes/prefixes.go
> +func GetPrefixes() [][]byte {
why is this [][]byte and not []byte? all the prefixes are bytes

2022-03-24 21:55 UTC, lyoshenka commented on db/prefixes/prefixes.go
> +	ACTIVATED_CLAIM_TXO_TYPE   = 1
why snake case here?

2022-03-24 21:55 UTC, lyoshenka commented on db/prefixes/prefixes.go
> +	n := 32 + 4 + 4 + 32 + 4 + 4 + 1 + 1 + 4 + 4 + 4 + 4
all this adding of byte counts is weird. is there a better way?

2022-03-24 21:55 UTC, lyoshenka commented on db/prefixes/prefixes.go
> +	n := 32 + 4 + 4 + 32 + 4 + 4 + 1 + 1 + 4 + 4 + 4 + 4
same in DBStateValueUnpack()

2022-03-24 21:55 UTC, lyoshenka commented on db/prefixes/prefixes.go
> +	Genesis        []byte
if this is a fixed size, should it be an array? or even a chainhash.Hash? https://github.com/lbryio/lbcd/blob/master/chaincfg/chainhash/hash.go#L25

2022-03-24 21:55 UTC, lyoshenka commented on db/prefixes/prefixes.go
> +	Genesis        []byte
i suggest using lbcd types as much as possible where it makes sense. if something is a Hash, make it a Hash. if its an Address, make it an Address.

2022-03-24 21:55 UTC, lyoshenka commented on db/prefixes/prefixes.go
> +func generic(voidstar interface{}, firstByte byte, function byte, functionName string) (interface{}, error) {
you really need to explain this one

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +	NOriginalClaimExpirationTime       = 262974
no need to start these with N

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +	NOriginalClaimExpirationTime       = 262974
and many of these are unused

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +	ClaimHash          []byte
all these hashes should be chainhash.Hash type

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +	return internal.NormalizeName(ps.name)
strongly suggest using lbcd's normalize function so its consistent

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +		log.Trace("ReadRow iterator not valid returning nil")
is this really no big deal? seems like an error to me but idk rocksdb

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +		FIXME:
needs fixing?

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +func GetProdDB(name string, secondaryPath string) (*ReadOnlyDBColumnFamily, func(), error) {
why return a cleanup function if its a) not used and b) on the db itself anyway?

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +func GetDBColumnFamlies(name string, secondayPath string, cfNames []string) (*ReadOnlyDBColumnFamily, error) {
typo: Famlies -> Families

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +	// TODO: assert tx_count not in self.db.tx_counts, f'boom {tx_count} in {len(self.db.tx_counts)} tx counts'
needs doing?

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +	ShutdownChan           chan struct{}
fyi this kind of stuff is usually done with sync.WaitGroup, but your way seems fine too

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +func DetectChanges(db *ReadOnlyDBColumnFamily) error {
this can be unexported

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +   def read_db_state(self):
still need this?

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +	//TODO: figure out a reasonable default and make it a constant
:eyes:

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +func RunGetBlocksAndFiltes(db *ReadOnlyDBColumnFamily) {
typo

2022-03-24 21:55 UTC, lyoshenka commented on db/db.go
> +	// whjy not needs to be len-1 because we start loading with the zero block
:eyes:

2022-03-24 21:55 UTC, lyoshenka commented on db/db_stack/db_stack.go
> +func (s *SliceBackedStack) TxCountsBisectRight(
every call of this uses the same bisect function. does it make sense to pass it in?

2022-03-24 21:55 UTC, lyoshenka commented on server/udp.go
> -	"github.com/lbryio/lbry.go/v2/extras/errors"
:+1: to this

dont use that error package anymore. if you do want to use one, use https://github.com/cockroachdb/errors

2022-03-24 22:18 UTC, jeffreypicard commented on db/prefixes/prefixes.go
> +	n := 32 + 4 + 4 + 32 + 4 + 4 + 1 + 1 + 4 + 4 + 4 + 4
I go back and forth on this. I think this is more clear than just hard coding the sum (maybe add the sum in a comment?), the even clearer way would be to make each of those constants a variable and sum them, but that seemed excessive.

2022-03-24 22:22 UTC, jeffreypicard commented on db/prefixes/prefixes.go
> +	n := 32 + 4 + 4 + 32 + 4 + 4 + 1 + 1 + 4 + 4 + 4 + 4
There's a sizeof in the "unsafe" library in go haha https://stackoverflow.com/questions/2113751/sizeof-struct-in-go but I'm not sure if that might return an implementation specific result due to padding, where here we are specifically taking the size of each individual element because we're packing them into a byte array.

2022-03-24 22:26 UTC, jeffreypicard commented on db/prefixes/prefixes.go
> +func generic(voidstar interface{}, firstByte byte, function byte, functionName string) (interface{}, error) {
Agreed. This is where we could possibly use generics from go 1.18 btw, I'm literally faking that here.

2022-03-24 22:32 UTC, jeffreypicard commented on db/db.go
> +	NOriginalClaimExpirationTime       = 262974
I agree the "N" can go. I copied these all over from the Python. where I believe they are similarly unused, because I thought it might be the defacto documentation.

2022-03-24 22:39 UTC, jeffreypicard commented on db/db.go
> +		log.Trace("ReadRow iterator not valid returning nil")
```
// Valid returns false only when an Iterator has iterated past either the
// first or the last key in the database.
func (iter *Iterator) Valid() bool {
	return C.rocksdb_iter_valid(iter.c) != 0
}
```
If our iterator was to try to go off the end of the db, or the front if we're going backwards, we need to check this.

2022-04-11 16:48 UTC, jeffreypicard commented on db/prefixes/prefixes.go
> +func GetPrefixes() [][]byte {
Because these need to be strings to actually specify column family names, but bytes when being used as prefixes, so I iterate over the [][]byte and convert the []byte to string for each when opening the full db.

2022-04-11 16:59 UTC, jeffreypicard commented on db/db.go
> +func GetProdDB(name string, secondaryPath string) (*ReadOnlyDBColumnFamily, func(), error) {
There's a few unit tests for the db that still use the cleanup function in this way, which is how it was originally, because I'm testing pieces of the db without fully building it and using it through the function interfaces and everything.

2022-04-11 17:00 UTC, lothropgauss commented on db/db.go
> +	// TODO: assert tx_count not in self.db.tx_counts, f'boom {tx_count} in {len(self.db.tx_counts)} tx counts'
No, this is an extra check that was in the python that isn't actually needed. I removed the comment.

2022-04-11 17:01 UTC, lothropgauss commented on db/db_stack/db_stack.go
> +func (s *SliceBackedStack) TxCountsBisectRight(
agreed, changed.

2022-04-15 14:15 UTC, lyoshenka commented on db/db_get.go
> +func GetExpirationHeightFull(lastUpdatedHeight uint32, extended bool) uint32 {
unclear what the diff between this and previous function is. whats a full expiration height?

2022-04-15 14:15 UTC, lyoshenka commented on db/db_resolve.go
> +func PrepareResolveResult(
should this function be exported? the name sounds like an internal function. in fact can you do a once-over on all functions to check what should and should not be exported? it may help to generate godocs and read them to see if they make sense as APIs for each thing

2022-04-15 14:15 UTC, lyoshenka commented on db/db_resolve.go
> +func PrepareResolveResult(
i requested docs from https://pkg.go.dev/github.com/lbryio/hub . might show up later

2022-04-15 14:15 UTC, lyoshenka commented on db/db_stack/db_stack.go
> +package db_stack
this is already a subpackage of `db`. it should be called `stack`, not `db_stack`

2022-04-15 14:15 UTC, lyoshenka commented on db/db_stack/db_stack.go
> +type SliceBackedStack struct {
assuming this package is named `stack`, this should just be `SliceBacked`. no need to put stack in the name again

2022-04-15 14:15 UTC, lyoshenka commented on db/iterator.go
> +// iterator.go contains the implementation for iterators on rocksdb used by the hub
should this be named iterator.go or iteroptions.go? it only has options stuff in it

2022-04-15 14:15 UTC, lyoshenka commented on db/iterator.go
> +// iterator.go contains the implementation for iterators on rocksdb used by the hub
or maybe just options.go

2022-04-15 14:15 UTC, lyoshenka commented on go.mod
>  	github.com/lbryio/lbry.go/v2 v2.7.2-0.20210625145058-2b155597bf57
you're using v2 and v3? what are you using from v2?

2022-04-15 14:15 UTC, lyoshenka commented on go.mod
>  	github.com/lbryio/lbry.go/v2 v2.7.2-0.20210625145058-2b155597bf57
also have you run `go mod tidy` recently?

2022-04-15 14:15 UTC, lyoshenka commented on internal/sort.go
> +import "sort"
seems like `search` is a better name than `sort`

2022-04-15 14:15 UTC, lyoshenka commented on main.go
> +	_ "net/http/pprof"
prolly here just for profiling, right?

2022-04-15 14:15 UTC, lyoshenka commented on internal/types.go
> +type HeightHash struct {
docs plz

2022-04-15 14:15 UTC, lyoshenka commented on scripts/build_and_test.sh
> +./protobuf/build.sh
do you see these changing often? id be careful cause diff versions of `protoc` could introduce cosmetic changes with big diffs that dont do much. i suggest that building protobufs should be a separate optional build step just for when they change

but if they change often, then its fine to leave it here

2022-04-15 14:15 UTC, lyoshenka commented on server/args.go
> +	DBCmd     = iota
what are cmd2 and cmd3? what do they mean?

2022-04-15 14:15 UTC, lyoshenka commented on server/server.go
> +	//TODO: is this the right place to load the db?
is it? maybe a separate function?  this ones long as it is

2022-04-15 14:28 UTC, jeffreypicard commented on db/db_get.go
> +func GetExpirationHeightFull(lastUpdatedHeight uint32, extended bool) uint32 {
That's just an internal distinction because it takes the optional boolean to use the extended expiration time. I added a comment.

2022-04-15 14:42 UTC, jeffreypicard commented on server/args.go
> +	DBCmd     = iota
These were things I added for testing, I removed them from the main function but missed removing them here. I'll get rid of them.

2022-04-20 13:55 UTC, jeffreypicard commented on main.go
> +	_ "net/http/pprof"
yeah

2022-04-29 14:46 UTC, jeffreypicard commented on go.mod
>  	github.com/lbryio/lbry.go/v2 v2.7.2-0.20210625145058-2b155597bf57
One straggler, just removed it.

2022-04-29 14:49 UTC, jeffreypicard commented on internal/sort.go
> +import "sort"
I'd normally agree, function I'm thinly wrapping comes straight from Go's "sort" package, so I thought this might make more sense.

2022-04-29 15:04 UTC, merged