Claim search port
lbryio/herald.go pull request #5
Opened 2021-05-18 10:05 UTC by jeffreypicard

MR for https://github.com/lbryio/hub/issues/2

Still need to add tests and fix the response.

2021-06-15 22:00 UTC, lyoshenka requested changes

2021-06-15 22:00 UTC, lyoshenka commented on Dockerfile
> +FROM debian:10-slim
what makes debian better than ubuntu or alpine?

2021-06-15 22:00 UTC, lyoshenka commented on build.sh
> +sudo docker build . -t lbry/hub:latest
`sudo` in a build script is not a good idea. i think you can use docker without sudo if you a dd yourself to the docker group

2021-06-15 22:00 UTC, lyoshenka commented on main.go
> +	"github.com/lbryio/hub/util"
plz sort imports like this

```
builtins

everything from lbryio 

everything else
```

2021-06-15 22:00 UTC, lyoshenka commented on util/util.go
> +package util
in my experience, packages like this turn into a disorganized heap of stuff. i recommend moving these into the package where you use them, or putting them somewhere in lbry.go as functions that normalize names and convert hashes to txids

2021-06-15 22:00 UTC, lyoshenka commented on util/util.go
> +package util
if you don't want them in lbry.go, you can make the package here. but make it about what its about instead of a generic `util`

2021-06-15 22:00 UTC, lyoshenka commented on server/search.go
> +func AddTermsField(arr []string, name string, q *elastic.BoolQuery) *elastic.BoolQuery {
i recommend putting `*q` as the first param in all these functions. its consistent and it's clear that you're adding to the query.

2021-06-15 22:00 UTC, lyoshenka commented on server/search.go
> +	if len(arr) > 0 {
you don't need this if check. if array is empty then the loop won't be run

2021-06-15 22:00 UTC, lyoshenka commented on server/search.go
> +	if len(arr) > 0 {
or if you did wanna leave it, Go prefers the exit-early strategy over many levels of nesting (let me know if this isn't clear and i'll show you an example)

2021-06-15 22:00 UTC, lyoshenka commented on server/search.go
> +func (s *Server) Search(ctx context.Context, in *pb.SearchRequest) (*pb.Outputs, error) {
this function is massive. you could break it up into building the query and then doing the search. and maybe into even smaller chunks

2021-06-15 22:00 UTC, lyoshenka commented on server/search.go
> +func getUniqueChannels(records []*record, client *elastic.Client, ctx context.Context, searchIndex string) ([]*pb.Output, map[string]*pb.Output) {
by convention `ctx` is generally the first param

2021-06-17 23:25 UTC, jeffreypicard commented on build.sh
> +sudo docker build . -t lbry/hub:latest
You're right, I set this up on a new ubuntu system and was too lazy to do that.

2021-06-17 23:26 UTC, jeffreypicard commented on util/util.go
> +package util
I think moving them into lbry.go is probably a good idea, I could see these being used elsewhere, I'll do that.

2021-06-17 23:27 UTC, jeffreypicard commented on server/search.go
> +func AddTermsField(arr []string, name string, q *elastic.BoolQuery) *elastic.BoolQuery {
Agreed

2021-06-17 23:31 UTC, jeffreypicard commented on server/search.go
> +	if len(arr) > 0 {
Yeah, I'll remove the check, I'm pretty sure I know what you're talking about with the exit-early strategy, you do the checks first for default cases and return in those, and then don't have the ifs around the main code. It's the same style as I learned in C, should have remembered that :)

2021-06-17 23:31 UTC, jeffreypicard commented on server/search.go
> +func getUniqueChannels(records []*record, client *elastic.Client, ctx context.Context, searchIndex string) ([]*pb.Output, map[string]*pb.Output) {
Makes sense

2021-06-17 23:36 UTC, jeffreypicard commented on Dockerfile
> +FROM debian:10-slim
I think I copied this from somewhere originally, but I can't find the original now, there wasn't really any thought behind it. Do we generally use alpine? I do think maybe ubuntu would be a bit bigger than needed since it's a static binary with no dependencies.

2021-06-18 02:38 UTC, jeffreypicard commented on Dockerfile
> +FROM debian:10-slim
Found it, this is why I used debian, copied from here https://github.com/lbryio/lbry-sdk/blob/master/docker/Dockerfile.wallet_server#L1

2021-06-21 20:46 UTC, lyoshenka commented on Dockerfile
> +FROM debian:10-slim
@shyba why did you use debian and not alpine or ubuntu?

2021-06-23 15:07 UTC, merged