Resolve json rpc
lbryio/herald.go pull request #57
Opened 2022-09-05 15:24 UTC by jeffreypicard

2022-09-06 19:27 UTC, moodyjon requested changes

2022-09-06 19:27 UTC, moodyjon commented on server/jsonrpc_service.go
> +	port := ":8080"
JSON port number should be a new thing in args.go, defaulting to 50001.

Then pass the args struct (or json parts of it) into StartJsonRPC111().

2022-09-06 19:27 UTC, moodyjon commented on requirements.txt
> +urllib3==1.26.11
Is this needed by scripts/version.py? Did it get created inadvertently?

2022-09-06 19:27 UTC, moodyjon commented on test_rpc.sh
> +curl --request POST 'localhost:8686/' \
Where does this port number come from? I would expect to see 8080.

Also does this need "/rpc" to match line 45 of jsonrpc_service.go?

I haven't been able to determine whether (Python) herald uses "/rpc" or any other path(s).

2022-09-07 05:16 UTC, jeffreypicard commented on requirements.txt
> +urllib3==1.26.11
Yes, this is needed by the version.py, it was intentional.

2022-09-07 05:17 UTC, jeffreypicard commented on server/jsonrpc_service.go
> +	port := ":8080"
Yup, I just added that. It's already carried in through the Server struct.

2022-09-07 05:18 UTC, jeffreypicard commented on test_rpc.sh
> +curl --request POST 'localhost:8686/' \
This is an old script added in by mistake, I'll move and change it.

2022-09-07 18:17 UTC, moodyjon approved these changes

2022-09-07 18:36 UTC, merged