integration testing scripts
lbryio/herald.go pull request #64
Opened 2022-09-21 10:24 UTC by jeffreypicard

some scripts for integration testing and a docker file for an action. Still need to figure out how to properly run a more realistic version in ci.

2022-09-21 18:09 UTC, moodyjon requested changes
Also, this appears to fall back on `/mnt/d/data/snapshot_1072108/lbry-rocksdb/` which I still don't know how to obtain, and I don't know how the GitHub runner gets a copy. I can live without it for now, but it would be great to be able to run locally.

2022-09-21 18:09 UTC, moodyjon commented on scripts/integration_tests.sh
> +WANT="encoding/hex: invalid byte: U+0047 'G'"
Yeah.... the scripthash ones are tricky. I don't have an example of constructing one. Lbry-sdk does not send them.

I haven't figured it out yet, but see:
https://github.com/btcsuite/btcd/search?p=1&q=AddressScriptHash&type=Code

2022-09-21 18:09 UTC, moodyjon commented on scripts/integration_tests.sh
> +WANT="${CHUNK_TEST_RES}"
Suggest substituting the value here, and eliminating `CHUNK_TEST_RES` as it's not reused by other tests.

2022-09-21 18:09 UTC, moodyjon commented on scripts/cicd_integration_test_runner.sh
> +
This is missing herald launch, and calling integration_tests.sh.

2022-09-21 18:09 UTC, moodyjon commented on scripts/integration_tests.sh
> +	if [ "${WANT}" -gt "${GOT}" ]; then
Greater than or equal to (`-ge`). At least for the one test using this, you wouldn't want GOT=0 to pass.

2022-09-22 17:02 UTC, moodyjon commented on scripts/integration_tests.sh
> +WANT="encoding/hex: invalid byte: U+0047 'G'"
Just found this. Purports to convert addr to scripthash:
https://github.com/checksum0/go-electrum/blob/b862ac442cf9/electrum/address.go#L14

2022-09-22 17:38 UTC, jeffreypicard commented
This definitely requires a local and complete snapshot of the current db at this point. Which requires running your own hub to have in general. Another big piece of what else I'm working on, but not something that in general will be documented here. Getting this running as part of a ci runner we do need to figure out, there's a dependency on hundreds of gigabytes of data to do a "real" smoke test on, so it's not clear the best way to do this.

2022-09-24 06:04 UTC, jeffreypicard commented on scripts/integration_tests.sh
> +	if [ "${WANT}" -gt "${GOT}" ]; then
I think I've just transposed the WANT and GOT, but the `-gt` is correct. I want a number greater than 0.

2022-09-24 06:28 UTC, jeffreypicard commented on scripts/integration_tests.sh
> +	if [ "${WANT}" -gt "${GOT}" ]; then
Actually, nvm, you are right.

2022-09-27 16:58 UTC, moodyjon requested changes

2022-09-27 16:58 UTC, moodyjon commented on db/db.go
> +	}
This should be before `db.NewIteratorCF()` and possibly before `grocksdb.NewDefaultReadOptions()`.

2022-09-27 16:58 UTC, moodyjon commented on db/db.go
> +			}
This whole block (`if opts.DB != nil {...`) should be after `it.Close()` and possibly after `ro.Destroy()`.

2022-09-27 16:58 UTC, moodyjon commented on db/db.go
> +	}
Position `[0]` is `DoneChan`, and position `[1]` is `ShutdownChan`. I think you mean to send to `ShutdownChan`, then receive from `DoneChan`.

I think this scheme could be simplified by having a single bidirectional chan. Send the shutdown message, then receive the done message on the same chan.

2022-09-27 16:58 UTC, moodyjon commented on db/db.go
> +				opts.DoneChan <- struct{}{}
If a thread is waiting on `ShutdownChan` in `db.Shutdown()` and holding the lock, this line (364) can't be reached. Send the done message just **before** locking, so `db.Shutdown()` can proceed.

2022-09-27 16:58 UTC, moodyjon commented on db/db.go
> +	// FIXME: Do we need to shutdown the iterators first?
My first thought: Yes of course. But...

...on investigating how this works, `ShutdownChan` works to stop `RunDetectChanges()`. Since that's a source of activity that may spawn new iterators, it's a good idea to stop that first so no new iterators are created. Also, consider waiting to receive the done message (`<- db.DoneChan`) before waiting on the iterators to be done.

The real grocksdb shutdown stuff that would break running iterators probably lies in `db.Cleanup()`.

2022-09-28 11:14 UTC, jeffreypicard commented on db/db.go
> +	}
II agree i used the wrong channels. I don't think you can really do the bi-directional thing though. It would create a new race conditional where I would send the notification then immediately read it off before the thread it was intended for did.

2022-09-28 11:18 UTC, jeffreypicard commented on db/db.go
> +			}
I agree.

2022-09-28 11:18 UTC, jeffreypicard commented on db/db.go
> +	}
sure

2022-09-28 11:24 UTC, jeffreypicard commented on db/db.go
> +				opts.DoneChan <- struct{}{}
good call

2022-09-28 12:01 UTC, moodyjon commented on db/db.go
> +	}
OK

2022-09-28 12:17 UTC, moodyjon requested changes

2022-09-28 12:17 UTC, moodyjon commented on db/db.go
> +				opts.DoneChan <- struct{}{}
The `opts.DoneChan <- struct{}{}` is still inside the critical section. It should be before `Lock()`.

2022-09-28 12:17 UTC, moodyjon commented on db/iteroptions.go
> +
I don't see anything using `WithDB`, so the new logic never becomes active. Perhaps make `NewIterateOptions()` take `db` as an argument?

2022-10-03 09:41 UTC, jeffreypicard commented on db/iteroptions.go
> +
Good call. I made the first change, and did changed the existing NewIterateOptions to use WithDB

2022-10-03 13:23 UTC, moodyjon approved these changes

2022-10-03 13:23 UTC, moodyjon commented on db/db.go
> +		opts.DB.OpenIterators[iterKey] = []chan struct{}{opts.DoneChan, opts.ShutdownChan}
One more tiny thing... At this point, it might be that db.Shutdown() has already been called. Because we are not yet in the map, the interruptRequested() func can't tell us anything. There should be a bool in DB that tells us Shutdown() has been called and no more registrations are being accepted. Set it in Shutdown() and check it here, exiting early if needed.

2022-10-04 17:25 UTC, merged