WIP: Server endpoints goroutine refactor
lbryio/herald.go pull request #69
Opened 2022-10-14 09:33 UTC by jeffreypicard

2022-10-14 14:42 UTC, moodyjon requested changes

2022-10-14 14:42 UTC, moodyjon commented on db/iteroptions.go
> +	DB         *ReadOnlyDBColumnFamily
Looks like this can be eliminated too. Only `opts.Grp` is really being used. As mentioned earlier, `opts.DB.ShutdownCalled` can be eliminated.

2022-10-14 14:42 UTC, moodyjon commented on db/db.go
> +		if opts.DB.ShutdownCalled && opts.Grp != nil {
`if opts.Grp != nil && interruptRequested(opts.Grp.Ch()) {`

This simplification eliminating `ShutdownCalled` is possible (I think) because you register the iterator with the stop group earlier. Now the registration happens in `opts.WithDB()`

2022-10-14 14:42 UTC, moodyjon commented on db/db.go
>  	ItMut                  sync.RWMutex
`OpenIterator`s, `ItMut` not needed anymore.

2022-10-14 14:42 UTC, moodyjon commented on server/server.go
> +		myDB.Grp = stop.NewDebug(grp)
Ahaa. So this is how it gets set. You might consider passing `grp` down into `LoadDatabase()`. So it gets initialized ASAP. Also, don't forget the `ReadonlyDBColumnFamilies` instance constructed in db_test.go.

2022-10-14 14:42 UTC, moodyjon commented on server/args.go
> +	args := &Args{
What is the reason to move/rename this? The package `server_test` seems like a fine location for it. Is it because it was in `federation_test.go` and shared by other test files?

2022-10-14 14:42 UTC, moodyjon commented on server/args.go
> +	GENESIS_HASH             = "9c89283ba0f3227f6c03b70216b9f665f0118d5e0fa729cedf4fb34d6a34f463"
Not needed.

2022-10-14 14:42 UTC, moodyjon commented on server/jsonrpc_service.go
> +		}
Please do the same registrations in session.go. It's in `addSession()` toward the bottom.

2022-10-14 14:42 UTC, moodyjon commented on server/jsonrpc_service.go
> +		}
I don't think you need separate service for each RPC. The reason we had to create them for `blockchain.xxx.yyy` RPCs was because there are TWO dots in the name.

Here the service would be named simply "server".

2022-10-14 14:44 UTC, moodyjon commented on server/args.go
> +	args := &Args{
I think you could create util_test.go and put it there if the file name (federation_test.go) is the concern.

2022-10-14 14:47 UTC, moodyjon commented on db/iteroptions.go
> +	o.Grp.Add(1)
This is great in that it enables other simplifications. However, we've got to be careful now about the use of IterOptions objects. Anytime one is constructed, it MUST later be used in `IterCF()`. Otherwise the refcount of active iterators leaks +1.

2022-10-15 13:53 UTC, jeffreypicard commented on server/args.go
> +	args := &Args{
Yes, this seems a little more general than to just be in `federation_test.go` I agree there's probably a need for a util_test package, I'll look at what we can add into something like that.

2022-10-15 15:06 UTC, jeffreypicard commented on db/iteroptions.go
> +	o.Grp.Add(1)
Yeah, I'm trying to weigh the pros and cons between requiring them in the "constructor" versus the flexibility of not requiring you have them in cases when they aren't needed.

2022-10-19 14:35 UTC, moodyjon approved these changes

2022-10-19 14:35 UTC, moodyjon commented on server/server.go
> +		// myDB.Grp.Add(1)
Not needed.

2022-10-19 14:35 UTC, moodyjon commented on db/db.go
> +	grp.Add(1)
Is this for the goroutine created in `RunDetectChanges()`? If so, I suggest placing it there.

2022-10-19 14:35 UTC, moodyjon commented on db/db_test.go
> +	db.Cleanup = toDefer
`db.Cleanup` is already set inside `GetProdDB()`, so not needed. I suggest standardizing on that approach. Have `GetProdDB`, `OpenAndFillTmpDBColumnFamilies`, etc all set `db.Cleanup` and eliminate the `toDefer` return.

Every time `GetProdDB` and others are called, do `defer db.Shutdown()` as you are doing here.

2022-10-19 14:35 UTC, moodyjon commented on db/db_test.go
> +	db.Cleanup = toDefer
Have `OpenAndFillTmpDBColumnFamilies()` assign `db.Cleanup = toDefer` inside to simplify this.

...Ditto all the other places calling `OpenAndFillTmpDBColumnFamilies()`.

2022-10-19 14:35 UTC, moodyjon commented on server/jsonrpc_blockchain_test.go
> +	grp := stop.New()
Should this be `NewDebug()` like other tests? Ditto all tests in this file.

2022-10-19 14:35 UTC, moodyjon commented on server/jsonrpc_blockchain_test.go
>  	defer toDefer()
`defer db.Shutdown()` to match style elsewhere.

2022-10-19 14:35 UTC, moodyjon commented on server/jsonrpc_blockchain_test.go
> +	defer db.Grp.Done()
Is this needed?

2022-10-19 14:35 UTC, moodyjon commented on server/session.go
> +			return
`sm.grp.Done()` here, and `sm.grp.Add(1)` in `(sm *SessionManager) start()` to account for goroutine running `manage()`.

2022-10-19 14:35 UTC, moodyjon commented on server/session.go
> +		log.Errorf("RegisterTCPService: %v\n", err)
`RegisterTCPService` -> `RegisterName`

2022-10-19 14:37 UTC, moodyjon commented on server/jsonrpc_service.go
> +
Reminder: Not needed.

2022-10-19 14:38 UTC, moodyjon commented on server/jsonrpc_service.go
> +
Reminder: Remove commented code.

2022-10-20 09:13 UTC, jeffreypicard commented on db/db_test.go
> +	db.Cleanup = toDefer
Agreed. Originally when I was developing this I was using the using the lower level db in some of the tests... I still might be actually I need to check. that's why I had a separate cleanup function I think I called it directly in the tests? Either way it's messy now and needs to be cleaned up.

2022-10-24 11:45 UTC, jeffreypicard commented on server/args.go
> +	args := &Args{
So I'm actually not going to do this right now. I just realized that the  jsonrpc_blockchain_test.go is in the server package, and relies heavily on using non-exported functions and structs. Technically I think the idiom is supposed to be that we put the tests in a "server_test" package and then use the server_test_pkg.go as a pivot to wrap and export all the parts in the server package that need it. This will be a pretty significant change in jsonrpc_blockchain_test.go though, so let's go that in a separate pr.

2022-10-25 01:52 UTC, moodyjon commented
Latest looks good, and all my comments are addressed, but I would encourage you to move away from creating separate `server_test` and `server` packages. Avoids the need to wrestle with creating exported versions of private methods. I think lbcd puts tests in the same package as the code they test.

2022-10-25 05:48 UTC, jeffreypicard commented
> Latest looks good, and all my comments are addressed, but I would encourage you to move away from creating separate `server_test` and `server` packages. Avoids the need to wrestle with creating exported versions of private methods. I think lbcd puts tests in the same package as the code they test.

So I think maybe this is a bit to do with style, but also around how we imagine this being used, a lot of places mention that it's best practices to put the tests in their own package, i.e. https://medium.com/@matryer/5-simple-tips-and-tricks-for-writing-unit-tests-in-golang-619653f90742 but that's more I guess if we imagined other people importing our library and using it from the outside, anything internal it makes sense to be in the same package I suppose.

2022-10-25 05:48 UTC, merged