WIP: Json rpc federation, search/getclaimbyid, and shutdown
lbryio/herald.go pull request #76
Opened 2022-11-13 12:01 UTC by jeffreypicard

2022-11-16 17:36 UTC, moodyjon commented on server/jsonrpc_claimtrie.go
> +	res, err := t.Server.Search(ctx, args)
OK, I see why you pass the `server.Server` into the session manager, and also store it in `ClaimtrieService`.

The python hub has a `SearchIndex` class which contains the search functionality of the `HubServerService`: https://github.com/lbryio/hub/blob/75d64f9dc6d3b2c913b8b10053bd3589e7a2e8eb/hub/herald/search.py#L29

The `SearchIndex` is passed off to the session manager instead of the whole `HubServerService`:
https://github.com/lbryio/hub/search?q=SearchIndex

Low priority to do this now, but splitting the search functionality (elastic search client, caches for search, etc) from `server.Server` into a `SearchIndex` struct/obj would be nice.

2022-11-17 19:02 UTC, moodyjon requested changes
I'm OK with having the `*Server` held inside `sessionManager` for now.

2022-11-17 19:02 UTC, moodyjon commented on signalsigterm.go
> -	shutdownRequestChannel = stopCh
It looks like `shutdownRequestChannel` is not hooked up to anything now -- nobody sends anything on it that I see. Hence you were able to add the code lines 52-54 in signal.go without triggering the spam problem again. It (`shutdownRequestChannel`) should be eliminated if it's not being used.

2022-11-17 19:02 UTC, moodyjon commented on server/notifier.go
> +			logrus.Warn("unknown notification type")
Probably need `peerNotification` case here.

2022-11-17 19:02 UTC, moodyjon commented on server/jsonrpc_federation.go
> +	return nil
Might as well complete this by adding sessionManager to PeersService (or other appropriate pointer). You have `sessionManager.peersSubs` already in place.

2022-11-17 19:02 UTC, moodyjon commented on server/session.go
> +		note, _ := notification.(peerNotification)
```
if !s.peersBool {
    return
}
```

2022-11-17 19:02 UTC, moodyjon commented on server/session.go
> +	peersBool bool
Rename `peersBool` -> `peersSub` to match comment.

2022-11-17 19:02 UTC, moodyjon commented on db/db.go
> +	// db.Grp.StopAndWait()
I don't see why this is disabled...

2022-11-17 22:04 UTC, jeffreypicard commented on server/notifier.go
> +			logrus.Warn("unknown notification type")
Maybe. We need to refactor this whole section of code, but I think that ends up getting handled by the catch-all `s.sessionManager.doNotify`

2022-11-17 22:15 UTC, jeffreypicard commented on signalsigterm.go
> -	shutdownRequestChannel = stopCh
I think I left this in because the intention is that this program can be run in either client or server mode, so there would ostensibly be a control endpoint that lets it be shutdown from a local only port that you could run the binary and send it a command to shutdown versus a ctrl+c. Maybe it's right to remove it for now anyways, but I feel like it's  feature we'll implement eventually.

2022-11-17 22:18 UTC, jeffreypicard commented on db/db.go
> +	// db.Grp.StopAndWait()
This should be removed. After some refactoring the stop group StopAndWait gets called in the higher up server Shutdown routine.

2022-11-17 22:38 UTC, jeffreypicard commented on server/jsonrpc_claimtrie.go
> +	res, err := t.Server.Search(ctx, args)
Yup, this definitely needs to be refactored in the future.

2022-11-19 00:02 UTC, moodyjon commented on server/notifier.go
> +			logrus.Warn("unknown notification type")
Never mind... I have been reading the code more, and NotifierChan is only populated with HeightHash notifications coming from observing the DB.

2022-11-19 00:10 UTC, moodyjon commented on server/jsonrpc_federation.go
> +
Ahh.... I meant register the subscription in the `sessionManager.peerSubs` map. Then inside `Server.notifyPeerSubs`, call `s.sessionManager.doNotify()` to forward a notification to the session-based mechanism.

The stuff in federation.go is more oriented towards grpc service and managing the list of known peers. When `server.peers.subscribe` comes in, it could be a client or (I suppose in the future) a peer herald.

2022-11-19 00:20 UTC, moodyjon requested changes
https://github.com/lbryio/herald.go/pull/76/files#r1026987357

2022-11-19 07:27 UTC, jeffreypicard commented on server/notifier.go
> +			logrus.Warn("unknown notification type")
I send it the new peers in federation.go `addPeer`

2022-11-19 07:34 UTC, jeffreypicard commented on server/jsonrpc_federation.go
> +
Ahh, yeah, just hooking it into the gRPC like this isn't going to quite work I suppose hahah

2022-12-07 14:08 UTC, moodyjon commented
https://github.com/lbryio/herald.go/pull/76/commits/f774823b2e1f953b6cba33627899923f42096c69

:thumbsup: :pray: Thank You!

2022-12-07 14:09 UTC, moodyjon commented on server/session.go
> +	switch note := notification.(type) {
Nice!

2022-12-07 14:10 UTC, moodyjon commented on server/args.go
> +	notifierPort := parser.Int("", "notifier-port", &argparse.Options{Required: false, Help: "notifier port", Default: DefaultNotifierPort})
You should add `validatePort` for these.

2022-12-07 14:18 UTC, moodyjon approved these changes
Suggest adding `validatePort` for the port num arguments.

2022-12-07 16:01 UTC, merged